import type { Metadata } from "next";

import "@public/css/globals.css";
import { OmokMainCanvas } from "@/components/omok-main-canvas";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create 3D Omock APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Suspense fallback={"로딩중입니다."}>
          <div className="h-screen flex justify-center items-center ">
            {children}
            <OmokMainCanvas cameraPosition={[0, 45, 30]} cameraFov={50} />
          </div>
        </Suspense>
      </body>
    </html>
  );
}
