import type { Metadata } from "next";

import "@public/css/globals.css";

export const metadata: Metadata = {
  title: "Create 3D Omock APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
